version: '3.7'

services:
  rails:
    build: containers/app
    image: app:1.0
    container_name: app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: "development"
      IS_DOCKER: "true"
      DB_USER_NAME: "root"
      DB_PASSWORD: "P@ssw0rd"
      DB_HOST: "mysql"
      EDITOR: "vim"
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/app
      - vendor-rails:/var/www/app/vendor
      - ~/.ssh:/root/.ssh
    command: "bash -c 'rm -f tmp/pids/server.pid && bundle && bin/rails db:create db:migrate && bin/rails db:seed && bundle exec puma -C config/puma.rb'"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --sort_buffer_size=1048576

  nginx:
    build:
      context: containers/nginx
    container_name: nginx
    volumes:
      - public-nginx-data:/webapp/public
      - ./tmp:/webapp/tmp
      - ./containers/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails

volumes:
  vendor-rails:
    driver: 'local'
  mysql-data:
    name: mysql
  public-nginx-data:
    name: nginx-pub
  tmp-nginx-data:
    name: nginx-tmp
